blacklist = [
    # Requires native dependencies
    "libressl-pnacl-sys",
    "pnacl-build-helper",

    # Not supported on stable
    "aster",
    "quasi",
    "quasi_codegen",
    "quasi_macros",

    # Apparently deleted
    "serde_macros",
    # Deprecated, causes old versions
    "serde_codegen",

    # Ecosystem is fragmented, only pull in via dependencies
    "openssl",
    "openssl-sys",
    "openssl-sys-extras",
    "openssl-verify",

    # Not supported on stable
    "redox_syscall",
    "redox_termios",

    # Not available on Linux
    "security-framework",
    "security-framework-sys",
    "core-foundation",
    "core-foundation-sys",

    # Not supported on stable
    "pin-api",
]

additions = [
    # Libz Blitz alumni and in progress crates
    "bitflags",
    "byteorder",
    "env_logger",
    "error-chain",
    "flate2",
    "gcc",
    "lazy_static",
    "log",
    "memmap",
    "mio",
    "num",
    "rayon",
    "reqwest",
    "tempdir",
    "threadpool",
    "url",
    "walkdir",

    # Libz Blitz todo list already available in rust-cookbook
    "base64",
    "chrono",
    "clap",
    "crossbeam",
    "csv",
    "data-encoding",
    "glob",
    "image",
    "num_cpus",
    "petgraph",
    "regex",
    "ring",
    "select",
    "serde",
    "serde_derive",
    "serde_json",
    "syslog",
    "tar",
    "toml",

    # TariLabs additions
    "libsecp256k1-rs",
    "curve25519-dalek",
    "ed25519-dalek",
    "x25519-dalek",
    "bulletproofs",
    "tari_utilities",
    "tari_crypto",
    "tari_core",
    "tari_infra_derive",
    "tari_shutdown",
    "tari_storage",
    "tari_test_utils",
    "tari_common",
    "tari_comms",
    "tari_comms_dht",
    "tari_p2p",
    "tari_mmr",
    "tari_service_framework",
    "tari_core",
    "tari_key_manager",
    "tari_wallet",
    "tari_pubsub"
]
